language: node_js

node_js:
   - 0.10

before_install:
   # - git submodule update --init --recursive

install:
   - npm install
   

before_script:
   # - git clone -q git://github.com/razab/nodejs-test-travis-ci.git
   # - cd casperjs; git checkout -q tags/1.1-beta1; cd ../
   # - export PATH=$PATH:`pwd`/casperjs/bin
   - npm install -g casperjs
   - phantomjs --version; casperjs --version

script: npm test